// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwllmsgqsihadfturirk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3bGxtc2dxc2loYWRmdHVyaXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODAzNjksImV4cCI6MjA2MzM1NjM2OX0.7lf_8ZfdVoVBYK1arfy-JZ8gTH0o63K0C2cWX3wilSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);